#
# Makefile for the kernel INC T3900 TDMB device drivers.
#
#########################################################

obj-y += t3900.o
  t3900-y := t3900_qfifo.o 
  t3900-y += t3900_rf_ctrl500.o
  t3900-y += t3900_inc_ficdec.o
  t3900-y += t3900_process.o
  t3900-y += t3900_interface.o
  t3900-y += t3900_bb.o