#
# Makefile for the kernel TDMB device drivers.
#
#########################################################

obj-y += mtv350.o
  mtv350-y += mtv350_bb.o 
  mtv350-y += raontv.o
  mtv350-y += raontv_port.o
  mtv350-y += raontv_rf.o
  mtv350-y += raontv_tdmb.o
  mtv350-y += raontv_cif_dec.o
#  mtv350-y += raontv_tsi_cif_parser.o