
obj-y   += tcc_fic_decoder.o
obj-y   += tcc_fic_fig0.o
obj-y   += tcc_fic_fig1.o


TDMBDIR := dmb/tdmb

EXTRA_CFLAGS += -Idrivers/$(TDMBDIR)/tcc3170/inc
EXTRA_CFLAGS += -Idrivers/$(TDMBDIR)/tcc3170/inc/tcpal
EXTRA_CFLAGS += -Idrivers/$(TDMBDIR)/tcc3170/inc/tcc_fic_decoder
