
obj-y   += tcpal_irq_handler.o
obj-y   += tcpal_debug.o
obj-y   += tcpal_queue.o
obj-y   += tcpal_linux.o
obj-y   += tcpal_io_cspi.o
obj-y   += tcpal_io_i2c.o


TDMBDIR := dmb/tdmb

EXTRA_CFLAGS += -Idrivers/$(TDMBDIR)/tcc3170/inc
EXTRA_CFLAGS += -Idrivers/$(TDMBDIR)/tcc3170/inc/tcpal
EXTRA_CFLAGS += -Idrivers/$(TDMBDIR)/tcc3170/inc/tcbd_stream_parser
EXTRA_CFLAGS += -Idrivers/$(TDMBDIR)/tcc3170/inc/tcbd_diagnosis
EXTRA_CFLAGS += -Idrivers/$(TDMBDIR)/tcc3170/inc/tcbd_fic_decoder
EXTRA_CFLAGS += -Idrivers/$(TDMBDIR)/tcc3170/inc/tcc_fic_decoder
