
obj-y   += tcbd_diagnosis.o


TDMBDIR := dmb/tdmb

EXTRA_CFLAGS += -Idrivers/$(TDMBDIR)/tcc3170/inc
EXTRA_CFLAGS += -Idrivers/$(TDMBDIR)/tcc3170/inc/tcpal
EXTRA_CFLAGS += -Idrivers/$(TDMBDIR)/tcc3170/inc/tcbd_diagnosis
