
obj-y   += tcbd_test_io.o


TDMBDIR := dmb/tdmb

EXTRA_CFLAGS += -Idrivers/$(TDMBDIR)/tcc3170/inc
EXTRA_CFLAGS += -Idrivers/$(TDMBDIR)/tcc3170/inc/tcpal
EXTRA_CFLAGS += -Idrivers/$(TDMBDIR)/tcc3170/inc/tcbd_parser
EXTRA_CFLAGS += -Idrivers/$(TDMBDIR)/tcc3170/inc/tcbd_diagnosis
