#
# Makefile for the kernel FCI FC8050 TDMB device drivers.
#
#########################################################

obj-y += fc8050.o

  fc8050-y := fc8050_bb.o 
  fc8050-y += fc8050_bbm.o
  fc8050-y += fc8050_demux.o
  fc8050-y += fc8050_hpi.o
  fc8050-y += fc8050_i2c.o
  fc8050-y += fc8050_isr.o
  fc8050-y += fc8050_ppi.o
  fc8050-y += fc8050_spi.o
  fc8050-y += fc8050_tun.o
  fc8050-y += fc8050_wrapper.o
  fc8050-y += fci_hal.o
  fc8050-y += fci_i2c.o
  fc8050-y += fci_tun.o